/**
 * tweak-api
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.tweakApi);
  }
}(this, function(expect, tweakApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new tweakApi.UserApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserApi', function() {
    describe('userConfirm', function() {
      it('should call userConfirm successfully', function(done) {
        //uncomment below and update the code to test userConfirm
        //instance.userConfirm(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userCount', function() {
      it('should call userCount successfully', function(done) {
        //uncomment below and update the code to test userCount
        //instance.userCount(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userCreate', function() {
      it('should call userCreate successfully', function(done) {
        //uncomment below and update the code to test userCreate
        //instance.userCreate(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userCreateChangeStreamGetUsersChangeStream', function() {
      it('should call userCreateChangeStreamGetUsersChangeStream successfully', function(done) {
        //uncomment below and update the code to test userCreateChangeStreamGetUsersChangeStream
        //instance.userCreateChangeStreamGetUsersChangeStream(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userCreateChangeStreamPostUsersChangeStream', function() {
      it('should call userCreateChangeStreamPostUsersChangeStream successfully', function(done) {
        //uncomment below and update the code to test userCreateChangeStreamPostUsersChangeStream
        //instance.userCreateChangeStreamPostUsersChangeStream(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userDeleteById', function() {
      it('should call userDeleteById successfully', function(done) {
        //uncomment below and update the code to test userDeleteById
        //instance.userDeleteById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userExistsGetUsersidExists', function() {
      it('should call userExistsGetUsersidExists successfully', function(done) {
        //uncomment below and update the code to test userExistsGetUsersidExists
        //instance.userExistsGetUsersidExists(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userExistsHeadUsersid', function() {
      it('should call userExistsHeadUsersid successfully', function(done) {
        //uncomment below and update the code to test userExistsHeadUsersid
        //instance.userExistsHeadUsersid(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userFind', function() {
      it('should call userFind successfully', function(done) {
        //uncomment below and update the code to test userFind
        //instance.userFind(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userFindById', function() {
      it('should call userFindById successfully', function(done) {
        //uncomment below and update the code to test userFindById
        //instance.userFindById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userFindOne', function() {
      it('should call userFindOne successfully', function(done) {
        //uncomment below and update the code to test userFindOne
        //instance.userFindOne(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userLogin', function() {
      it('should call userLogin successfully', function(done) {
        //uncomment below and update the code to test userLogin
        //instance.userLogin(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userLogout', function() {
      it('should call userLogout successfully', function(done) {
        //uncomment below and update the code to test userLogout
        //instance.userLogout(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeCountAccessTokens', function() {
      it('should call userPrototypeCountAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeCountAccessTokens
        //instance.userPrototypeCountAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeCreateAccessTokens', function() {
      it('should call userPrototypeCreateAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeCreateAccessTokens
        //instance.userPrototypeCreateAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeDeleteAccessTokens', function() {
      it('should call userPrototypeDeleteAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeDeleteAccessTokens
        //instance.userPrototypeDeleteAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeDestroyByIdAccessTokens', function() {
      it('should call userPrototypeDestroyByIdAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeDestroyByIdAccessTokens
        //instance.userPrototypeDestroyByIdAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeFindByIdAccessTokens', function() {
      it('should call userPrototypeFindByIdAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeFindByIdAccessTokens
        //instance.userPrototypeFindByIdAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeGetAccessTokens', function() {
      it('should call userPrototypeGetAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeGetAccessTokens
        //instance.userPrototypeGetAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeUpdateAttributesPatchUsersid', function() {
      it('should call userPrototypeUpdateAttributesPatchUsersid successfully', function(done) {
        //uncomment below and update the code to test userPrototypeUpdateAttributesPatchUsersid
        //instance.userPrototypeUpdateAttributesPatchUsersid(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeUpdateAttributesPutUsersid', function() {
      it('should call userPrototypeUpdateAttributesPutUsersid successfully', function(done) {
        //uncomment below and update the code to test userPrototypeUpdateAttributesPutUsersid
        //instance.userPrototypeUpdateAttributesPutUsersid(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userPrototypeUpdateByIdAccessTokens', function() {
      it('should call userPrototypeUpdateByIdAccessTokens successfully', function(done) {
        //uncomment below and update the code to test userPrototypeUpdateByIdAccessTokens
        //instance.userPrototypeUpdateByIdAccessTokens(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userReplaceById', function() {
      it('should call userReplaceById successfully', function(done) {
        //uncomment below and update the code to test userReplaceById
        //instance.userReplaceById(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userReplaceOrCreate', function() {
      it('should call userReplaceOrCreate successfully', function(done) {
        //uncomment below and update the code to test userReplaceOrCreate
        //instance.userReplaceOrCreate(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userResetPassword', function() {
      it('should call userResetPassword successfully', function(done) {
        //uncomment below and update the code to test userResetPassword
        //instance.userResetPassword(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userUpdateAll', function() {
      it('should call userUpdateAll successfully', function(done) {
        //uncomment below and update the code to test userUpdateAll
        //instance.userUpdateAll(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userUpsertPatchUsers', function() {
      it('should call userUpsertPatchUsers successfully', function(done) {
        //uncomment below and update the code to test userUpsertPatchUsers
        //instance.userUpsertPatchUsers(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userUpsertPutUsers', function() {
      it('should call userUpsertPutUsers successfully', function(done) {
        //uncomment below and update the code to test userUpsertPutUsers
        //instance.userUpsertPutUsers(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userUpsertWithWhere', function() {
      it('should call userUpsertWithWhere successfully', function(done) {
        //uncomment below and update the code to test userUpsertWithWhere
        //instance.userUpsertWithWhere(pet, function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
